spring:
  profiles:
    active: development
  jpa:
    hibernate:
      ddl-auto: update
#  datasource:
#    url: jdbc:mysql://localhost:3306/bookstore
#    username: root
#    password: 1234
#    driverClassName: com.mysql.jdbc.Driver
#    testOnBorrow: true
#    validationQuery: SELECT 1
server:
  port: 8085